[package]
name = "macaroon"
version = "0.1.1"
authors = ["Jack Lund <jackl@geekheads.net>"]
description = "Fully functional implementation of macaroons in Rust"
documentation = "https://docs.rs/macaroon"
homepage = "https://github.com/jacklund/libmacaroon-rs"
repository = "https://github.com/jacklund/libmacaroon-rs"
keywords = ["macaroon", "cookies", "authorization", "credentials"]
categories = ["cryptography"]
license = "MIT"

[dependencies]
log = "0.3.9"
rustc-serialize = "0.3.22"
serde = { version= "1.0", features = ["derive"] }
serde_json = "1.0"
sodiumoxide = "0.2"

[dev-dependencies]
env_logger = "0.7"
time = "0.1.44"
